os:
  - linux
  - osx
dist: trusty
osx_image: xcode10.3

language: rust
rust:
  - stable
  - beta
  - nightly

cache:
  cargo: true

notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

script:
  - cargo +$TRAVIS_RUST_VERSION test --verbose

